name:                haskell-game
version:             0.1.0.0
github:              "Fizzixnerd/haskell-game"
license:             MIT
author:              "Matt Walker and InThisStyle10/6"
maintainer:          "matt.g.d.walker@gmail.com"
copyright:           "2018 Matt Walker and InThisStyle10/6"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A game, written in Haskell.
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Fizzixnerd/haskell-game#readme>

dependencies:
- ALUT
- foreign-resource-hs
- assimp-hs
- FontyFruity
- GLFW-b
- JuicyPixels
- OpenAL
- OpenGL
- Rasterific
- StateVar
- ObjectName
- assimp-hs
- base >= 4.7 && < 5
- bullet-hs
- bytestring
- classy-prelude
- containers
- exceptions
- ghc
- ghc-paths
- gl
- lens
- lens-action
- linear
- monad-logger
- mtl
- netwire
- netwire-input
- netwire-input-glfw
- plugin
- haskell-graphics-binding
- resourcet
- safe-exceptions
- singletons
- text
- vector
- vinyl
- wavefront
- unliftio-core

ghc-options:

library:
  source-dirs: src

executables:
  haskell-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall

    dependencies:
    - haskell-game

tests:
  haskell-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall

    dependencies:
    - haskell-game
