name:                haskell-game
version:             0.1.0.0
github:              "githubuser/haskell-game"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskell-game#readme>

dependencies:
- ALUT
- assimp-hs
- FontyFruity
- GLFW-b
- JuicyPixels
- OpenAL
- OpenGL
- Rasterific
- StateVar
- ObjectName
- base >= 4.7 && < 5
- bullet-hs
- bytestring
- classy-prelude
- containers
- exceptions
- ghc
- ghc-paths
- gl
- lens
- lens-action
- linear
- monad-logger
- mtl
- netwire
- netwire-input
- netwire-input-glfw
- plugin
- graphics-binding
- resourcet
- safe-exceptions
- singletons
- text
- vector
- vinyl
- wavefront
- unliftio-core

ghc-options:
  - -fPIC

library:
  source-dirs: src

executables:
  haskell-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fPIC

    dependencies:
    - haskell-game

tests:
  haskell-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fPIC
    dependencies:
    - haskell-game
